# Generated by Django 2.2 on 2020-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200912_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='session_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
