# Generated by Django 2.2 on 2020-09-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200914_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='session_id',
            new_name='device_id',
        ),
    ]
