# Generated by Django 2.2 on 2020-05-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200531_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
