# Generated by Django 2.2 on 2020-06-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200610_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='units',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
