# Generated by Django 2.2 on 2020-06-22 13:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200618_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, unique=True),
        ),
    ]
