# Generated by Django 2.2 on 2020-06-22 14:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200622_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=('customer__username', 'id')),
        ),
    ]
