# Generated by Django 2.2 on 2020-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Shipment'), ('In TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], max_length=20, null=True),
        ),
    ]
