# Generated by Django 2.2 on 2020-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200709_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('SORTING', 'Sorting'), ('SHIPMENT', 'In Transit'), ('DELIVERED', 'Delivered')], max_length=20, null=True),
        ),
    ]
